# Dependencies
highlighter:      rouge

markdown:         kramdown

# Permalinks
permalink:        none

# Setup
title:            LeiosLabs
tagline:          'Asking real questions. Explaining the answers.'
description:      'Asking real questions. Explaining the answers.'
url:              https://leios.github.io
baseurl:          /

author:
  name:           'James Schloss'
  url:            https://twitter.com/leiosos

github:
  repo:           https://github.com/leios

gems:
  - jekyll-feed
