using Documenter

makedocs(
    sitename="Leios Labs",
    authors="James Schloss (Leios)",
    pages = [
        "General Information" => "index.md",
        "About Me" => "content/about.md",
        "GPU Kernel Handbook" => Any[
            "Welcome" => "gpu-handbook/index.md",
            "Reviewer Guidelines" => "gpu-handbook/reviewers.md",
            "About the Author" => "gpu-handbook/about_me.md",
            "Introduction" => "gpu-handbook/intro.md",
            "All the Ways to GPU" => "gpu-handbook/abstractions.md",
        ],
        "Scribblings" => Any[
            "Welcome" => "scribbleios/index.md",
            "2024" => Any[
                "A Second Chance" => "scribbleios/2024/September/28.md",
                "The Livestreaming Accident" => "scribbleios/2024/February/20.md",
            ],
            "2023" => Any[
                "The Read Message" => "scribbleios/2023/2023.md",
            ],
            "2022" => Any[
                "The Commute" => "scribbleios/2022/August/01.md",
                "The USB Hero" => "scribbleios/2022/May/10.md",
                "The Modern Blacksmith" => "scribbleios/2022/April/11.md",
                "The Humbler" => "scribbleios/2022/April/07.md",
                "The Conscious Actor" => "scribbleios/2022/March/30.md",
                "Digital Selves" => "scribbleios/2022/February/24.md",
                "Walking to School" => "scribbleios/2022/February/15.md",
                "Wikipedia: Peter Shelly" => "scribbleios/2022/February/11.md",
                "Bittersweet Memories" => "scribbleios/2022/February/02.md",
                "Academic Correspondences" => "scribbleios/2022/February/01.md",
                "The Beowulf Poet" => "scribbleios/2022/January/31.md",
                "A Waste of Time" => "scribbleios/2022/January/23.md",
                "Describing a Tree" => "scribbleios/2022/January/02.md",
                "The Future" => "scribbleios/2022/January/06.md",
            ],
            "2021" => Any[
                "The NPC" => "scribbleios/2021/December/12.md",
                "A Talentless Student" => "scribbleios/2021/February/03.md",
                "The Master's Disciple" => "scribbleios/2021/February/02.md",
                "The Potion Master" => "scribbleios/2021/February/01.md",
                "The G00Gl3 Interview" => "scribbleios/2021/January/31.md",
                "A Mother's Love" => "scribbleios/2021/January/30.md",
                "The Creation Machine" => "scribbleios/2021/January/29.md",
                "The Great Collapse" => "scribbleios/2021/January/28.md",
                "Losing Myself" => "scribbleios/2021/January/27.md",
                "Merfolk" => "scribbleios/2021/January/26.md",
                "The Super Couple" => "scribbleios/2021/January/22.md",
                "The Girlfriend" => "scribbleios/2021/January/03.md",
                "The Anti-Poem" => "scribbleios/2021/January/02.md",
                "Who I Want to Be" => "scribbleios/2021/January/01.md",
            ],
            "2020" => Any[
                "Reincarnated Happiness" => "scribbleios/2020/December/27.md",
                "The Helpful Demon" => "scribbleios/2020/December/26.md",
                "Sophia and Aheb" => "scribbleios/2020/December/25.md",
                "Age Regression" => "scribbleios/2020/December/24.md",
                "Shy Gal" => "scribbleios/2020/December/23.md",
                "This is Not the End" => "scribbleios/2020/December/12.md",
                "All the Right Questions" => "scribbleios/2020/December/11.md",
                "Returning to the Sea" => "scribbleios/2020/December/10.md",
                "How Elves are Made" => "scribbleios/2020/December/09.md",
                "The American Hero" => "scribbleios/2020/December/08.md",
                "Jim" => "scribbleios/2020/December/07.md",
                "The Cult of Vi" => "scribbleios/2020/December/06.md",
                "Rhyming Truths" => "scribbleios/2020/December/05.md",
                "The Blind Dragon" => "scribbleios/2020/December/04.md",
                "Santa Stole the Money" => "scribbleios/2020/December/03.md",
                "The Angel of Mercy" => "scribbleios/2020/December/02.md",
                "The Genie Order" => "scribbleios/2020/December/01.md",
                "The Bargaining Protagonist" => "scribbleios/2020/November/30.md",
                "Raindrops on the Window" => "scribbleios/2020/November/29.md",
                "Happy Habitat" => "scribbleios/2020/October/06.md",
                "Another Castle" => "scribbleios/2020/October/05.md",
                "Glitching" => "scribbleios/2020/October/04.md",
                "Mirrors on the Wall" => "scribbleios/2020/October/03.md",
                "The Forest Guardian" => "scribbleios/2020/October/02.md",
                "The Prince of Time" => "scribbleios/2020/October/01.md",
                "The Sword and Shield" => "scribbleios/2020/July/6.md",
                "The Unsettling Sandwich" => "scribbleios/2020/July/4.md",
                "Afraid of the Light" => "scribbleios/2020/July/3.md",
                "The Demon Professor" => "scribbleios/2020/July/2.md",
                "Tree Traversing Super Power" => "scribbleios/2020/July/1.md",
                "Luminescent Love Story" => "scribbleios/2020/June/30.md",
                "Becoming Anything" => "scribbleios/2020/June/29.md",
            ],
        ],
    ],
)

deploydocs(;
    repo="github.com/leios/leios.github.io",
    versions = nothing,
)
